name: Deploy app to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: 'ardi.eshghi@gmail.com'
        env:
          HD_AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          HD_AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          HD_ADMIN_USERNAME: ${{secrets.ADMIN_USERNAME}}
          HD_ADMIN_PASSWORD: ${{secrets.ADMIN_PASSWORD}}
          HD_S3_BUCKET: ${{secrets.S3_BUCKET}}
